# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PurpleWiki
version:      0.93
version_from: 
installdirs:  site
requires:
    AppConfig:                     1.55
    CGI:                           0
    CGI::Carp:                     0
    CGI::Session:                  0
    Date::Manip:                   0
    DB_File:                       0
    IO::File:                      0
    LWP::UserAgent:                0
    Template:                      0
    Text::Diff:                    0
    Text::Wrap:                    0
    XML::RSS:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
